# Generated by Django 3.1.7 on 2021-03-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='atcoder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('url', models.CharField(max_length=200, null=True)),
                ('start_time', models.CharField(max_length=200, null=True)),
                ('end_time', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='codechef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('url', models.CharField(max_length=200, null=True)),
                ('start_time', models.CharField(max_length=200, null=True)),
                ('end_time', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='codeforces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('url', models.CharField(max_length=200, null=True)),
                ('start_time', models.CharField(max_length=200, null=True)),
                ('end_time', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='hackerearth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('url', models.CharField(max_length=200, null=True)),
                ('start_time', models.CharField(max_length=200, null=True)),
                ('end_time', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='hackerrank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('url', models.CharField(max_length=200, null=True)),
                ('start_time', models.CharField(max_length=200, null=True)),
                ('end_time', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='leetcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('url', models.CharField(max_length=200, null=True)),
                ('start_time', models.CharField(max_length=200, null=True)),
                ('end_time', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='topcoder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('url', models.CharField(max_length=200, null=True)),
                ('start_time', models.CharField(max_length=200, null=True)),
                ('end_time', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
